# Generated by Django 4.0.4 on 2022-04-19 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqnum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
                ('count', models.IntegerField(default=0)),
                ('shipment_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('truck_package_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('arrive warehouse', 'arrive warehouse'), ('delivering', 'delivering'), ('loading', 'loading'), ('traveling', 'traveling'), ('idle', 'idle')], default='idle', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('shipment_id', models.IntegerField(unique=True)),
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('delivered', 'delivered'), ('delivering', 'delivering'), ('pick_up', 'pick_up'), ('loading', 'loading')], default='pick_up', max_length=32)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upswebsite.truck')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upswebsite.user')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveringTruck',
            fields=[
                ('whid', models.IntegerField(primary_key=True, serialize=False)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upswebsite.truck')),
            ],
        ),
    ]
