# Generated by Django 4.0.4 on 2022-04-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upswebsite', '0005_alter_package_status_alter_truck_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('loading', 'loading'), ('delivering', 'delivering'), ('pick_up', 'pick_up'), ('delivered', 'delivered')], default='pick_up', max_length=32),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('loading', 'loading'), ('idle', 'idle'), ('arrive warehouse', 'arrive warehouse'), ('delivering', 'delivering'), ('traveling', 'traveling')], default='idle', max_length=32),
        ),
    ]
