# Generated by Django 4.0.4 on 2022-04-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upswebsite', '0013_alter_truck_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('loading', 'loading'), ('delivering', 'delivering'), ('delivered', 'delivered'), ('pick_up', 'pick_up')], default='pick_up', max_length=32),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('loading', 'loading'), ('idle', 'idle'), ('arrive warehouse', 'arrive warehouse'), ('traveling', 'traveling'), ('delivering', 'delivering')], default='idle', max_length=32),
        ),
    ]
