# Generated by Django 4.0.4 on 2022-04-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upswebsite', '0043_alter_package_status_alter_truck_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('pick_up', 'pick_up'), ('loading', 'loading'), ('delivered', 'delivered'), ('delivering', 'delivering')], default='pick_up', max_length=32),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('arrive warehouse', 'arrive warehouse'), ('delivering', 'delivering'), ('loading', 'loading'), ('idle', 'idle'), ('traveling', 'traveling')], default='idle', max_length=32),
        ),
    ]
