# Generated by Django 4.0.4 on 2022-04-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upswebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ack',
            name='world_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveringtruck',
            name='world_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='world_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='world_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sequence',
            name='world_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truck',
            name='world_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='world_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('pick_up', 'pick_up'), ('loading', 'loading'), ('delivered', 'delivered'), ('delivering', 'delivering')], default='pick_up', max_length=32),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('delivering', 'delivering'), ('arrive warehouse', 'arrive warehouse'), ('traveling', 'traveling'), ('loading', 'loading'), ('idle', 'idle')], default='idle', max_length=32),
        ),
    ]
